Repository impostor-commerce/impostor-commerce-backend, pull requests merged in 2024-12, with the labels that each got.

#42 [#20] test: B2C 상품 단건 조회 테스트 코드 작성
  b2c/src/main/java/com/sparta/b2c/config/JpaConfig.java
  b2c/src/main/java/com/sparta/b2c/product/dto/response/ProductResponse.java
  b2c/src/main/java/com/sparta/b2c/product/service/ProductService.java
  b2c/src/test/java/com/sparta/b2c/B2cApplicationTests.java
  b2c/src/test/java/com/sparta/b2c/product/service/ProductServiceUnitTest.java
  domain/src/main/java/com/sparta/impostor/commerce/backend/domain/product/entity/Product.java
Labels: 🔭test

#51 [#16] feat: B2B 화면에서 특정 상품 조회(단건)
  b2b/src/main/java/com/sparta/b2b/product/controller/ProductController.java
  b2b/src/main/java/com/sparta/b2b/product/dto/response/ProductSearchResponse.java
  b2b/src/main/java/com/sparta/b2b/product/service/ProductService.java
Labels: 🔥feature

#50 [#17] feat: B2C 상품 검색
  b2c/src/main/java/com/sparta/b2c/B2cApplication.java
  b2c/src/main/java/com/sparta/b2c/product/controller/ProductController.java
  b2c/src/main/java/com/sparta/b2c/product/dto/request/ProductSearchRequest.java
  b2c/src/main/java/com/sparta/b2c/product/dto/response/PageProductResponse.java
  b2c/src/main/java/com/sparta/b2c/product/dto/response/ProductResponse.java
  b2c/src/main/java/com/sparta/b2c/product/service/ProductService.java
  domain/src/main/java/com/sparta/impostor/commerce/backend/domain/product/enums/Category.java
  domain/src/main/java/com/sparta/impostor/commerce/backend/domain/product/repository/ProductRepository.java
  domain/src/main/java/com/sparta/impostor/commerce/backend/domain/product/repository/ProductRepositoryQuery.java
  domain/src/main/java/com/sparta/impostor/commerce/backend/domain/product/repository/ProductRepositoryQueryImpl.java
Labels: 🔥feature

#65 [#53] test: B2C 상품 검색 & 상품 단건 조회 테스트코드
  b2c/build.gradle
  b2c/src/test/java/com/sparta/b2c/product/service/ProductServiceIntegrationTest.java
  b2c/src/test/java/com/sparta/b2c/product/service/ProductServiceUnitTest.java
  b2c/src/test/resources/application.yml
Labels: 🔭test

#102 [#97] feat: CI/CD 추가
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  admin/appspec.yml
  admin/scripts/deploy.sh
  admin/src/main/resources/application-prod.yml
  b2b/appspec.yml
  b2b/scripts/deploy.sh
  b2b/src/main/resources/application-prod.yml
  b2c/appspec.yml
  b2c/scripts/deploy.sh
  b2c/src/main/resources/application-prod.yml
  b2c/src/test/java/com/sparta/b2c/product/service/ProductServiceIntegrationTest.java
  b2c/src/test/java/com/sparta/b2c/product/service/RelatedProductRetrieveTest.java
  common/src/test/java/com/sparta/common/CommonApplicationTests.java
  domain/src/test/java/com/sparta/impostor/commerce/backend/ImpostorCommerceBackendApplicationTests.java
Labels: 🔥feature, 🔭test

#116 [#115]hotfix: B2B 상품 조금 큰 이미지 S3에 업로드가 안되는 버그 해결
  b2b/src/main/java/com/sparta/b2b/fileUpload/service/S3ManageService.java
Labels: 🚨fix

#117 [#107] Feat: Product영역 IllegalArgumentException & @CheackAuth 추가
  admin/src/main/java/com/sparta/admin/product/controller/ProductApprovalController.java
  admin/src/main/java/com/sparta/admin/product/controller/ProductController.java
  admin/src/main/java/com/sparta/admin/product/service/ProductApprovalService.java
Labels: 🔥feature

#123 [#119] Feat: admin 영역 MDC 기반의 traceId 추적과 AOP를 통한 로그 로깅의 결합
  admin/src/main/resources/application.yml
  admin/src/main/resources/logback-spring.xml
  b2b/src/main/resources/logback-spring.xml
  b2c/src/main/resources/logback-spring.xml
  common/src/main/java/com/sparta/common/config/LogConfig.java
  common/src/main/java/com/sparta/common/interceptor/LoggingInterceptor.java
  common/src/main/java/com/sparta/common/logging/LoggingAspect.java
  common/src/main/java/com/sparta/common/logging/TraceIdFilter.java
Labels: 🔥feature

#128 [#119] Feat: MDC, TraceId를 활용한 로그 추적 구현
  .gitignore
  admin/src/main/resources/logback-spring.xml
  b2b/src/main/resources/logback-spring.xml
  b2c/src/main/resources/logback-spring.xml
  common/src/main/java/com/sparta/common/interceptor/LoggingInterceptor.java
  common/src/main/java/com/sparta/common/logging/LoggingAspect.java
  common/src/main/java/com/sparta/common/logging/TraceIdFilter.java
Labels: 🔥feature
